FROM python:3.12-slim

SHELL ["/bin/bash", "-c"]

ENV PYTHONUNBUFFERED=1

EXPOSE 22
VOLUME ["/app"]

WORKDIR /app

RUN apt-get update
# Install dev dependancies
RUN apt-get install -y --no-install-recommends \
    make
RUN python3 -m pip install --upgrade pip
RUN if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
RUN if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
# Setup SSH with root login
RUN apt-get install -y openssh-server \
    && mkdir /var/run/sshd \
    && echo 'root:password' | chpasswd \
    && sed -i 's/\#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

ENTRYPOINT ["/usr/sbin/sshd", "-D"]
