name: Integration

on:
  push:
    branches:
      - '**'
    paths:
      - '**.py'
      - '.github/**'

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -e .[dev]

      - name: Check coding style
        run: |
          make lint

      - name: Run tests
        shell: bash
        run: |
          make test

      - name: Generate code coverage badge
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          disable_search: true
          files: coverage.info
          token: ${{ secrets.CODECOV_TOKEN }}
