name: Create release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

env:
  addon_name: script.service.betaseries-watched
  addon_version: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure addon.xml
        run: |
          sed addon.xml \
              -e "s/{{ addon_name }}/${addon_name}/" \
              -e "s/{{ addon_version }}/${addon_version}/" \
              -e "/{{ addon_changelog }}/r changelog.txt" \
              -e "s/^.*{{ addon_changelog }}/${addon_version} (`date +'%Y-%m-%d'`)/"
      - name: Build add-on
        run: |
          mkdir .${addon_name}
          cp -r * .${addon_name}
          mv .${addon_name} ${addon_name}
          zip -r ${addon_name}_${addon_version}.zip ${addon_name}
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          prerelease: false
          draft: false
      - name: Upload release asset
        #id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ addon_name }}_${{ addon_version }}.zip
          asset_name: ${{ addon_name }}_${{ addon_version }}.zip
          asset_content_type: application/zip
